[Match]
Distribution=arch

[Content]
Packages=
        amd-ucode
        base
        bluez
        bluez-utils
        cups
        cups-pdf
        dmidecode
        espeakup
        flatpak
        fprintd
        gamemode
        glibc-locales
        inetutils
        intel-ucode
        linux
        linux-firmware
        man-db
        mesa
        networkmanager
        orca
        powertop
        power-profiles-daemon
        speech-dispatcher
        sudo 
        tar
        thermald
        unrar
        unzip
        usbutils
        vulkan-radeon
        vulkan-intel





        
