[Match]
Distribution=arch

[Content]
Packages=
        evolution-data-server
        gdm
        gnome-backgrounds
        gnome-control-center
        gnome-disk-utility
        gnome-initial-setup
        gnome-keyring
        gnome-remote-desktop
        gnome-session
        gnome-shell
        gnome-user-share
        grilo-plugins
        gvfs-afc
        gvfs-dnssd
        gvfs-goa 
        gvfs-gphoto2
        gvfs-mtp
        gvfs-nfs
        gvfs-onedrive
        gvfs-smb
        gvfs-wsdd
        nautilus
        ptyxis
        rygel
        tecla
        xdg-desktop-portal-gnome